site_name: జయాంజనేయ

nav:
    - Home: index.md
    - Audio : ./audio.md
    - About : ./about.md
    - Pictures : ./pictures.md
    - Program : ./program.md
    - శ్రీపాదుక : ./sripaduka.md
    - మీరాకళాజ్యోత్స్న : ./ramalingaswamy.md
    - బాల చైతన్యం : ./balachaitanyam.md
    - Register: ./register.md


theme: material

use_directory_urls: true

extra_css:
    - ./css/style.css
markdown_extensions:
    - mdx_custom_span_class
    - markdown_include.include
